Pan-Canadian-Genome-Library/daco

.github/pull_request_template.md

Adds a Pull Request template to standardize PR descriptions and provide a developer checklist for self-review before submitting the request.
- Adds `.github/pull_request_template.md`

chore: Add Pull Request template

---

apps/ui/src/components/Footer.tsx
apps/ui/src/components/Header.tsx
apps/ui/src/components/layouts/ContentWrapper.tsx
apps/ui/src/global/hooks/useMinWidth.ts
apps/ui/src/index.css
apps/ui/src/pages/App.tsx
apps/ui/src/pages/index.tsx

Implements responsiveness to the homepage, menu/header bar, as well as the footer. Fixes some issues with large displays (1080p and above) by limiting the max width for better readability. Finally, also adds A11Y fixes and tweaks to the UI to further match the mockup.
- https://github.com/Pan-Canadian-Genome-Library/daco/issues/81
- Added `useMinWidth.ts` as a globally accessible react hook. 
- This is used to programatically get the current screen width, used in conjunction with `Breakpoints` to align with Ant Design's breakpoint sizes. 
- Particularly useful for the vast majority of antd components which don't have their own built in responsive props like `Col` does.
- Helps prepare for adding the device size warning mentioned in #82.
- On large screen sizes, the website would stretch …

#81: Build homepage for mobile and tablet

---

apps/api/src/resources/swagger.yaml
apps/api/src/routes/application-router.ts

Chore / Rename Applications Edit route
Standardize `/applications/edit` route, caught in PR discussion related to #90 
[#90](https://github.com/Pan-Canadian-Genome-Library/daco/pull/90#discussion_r1878679708)
- Standardized `/applications` path for API endpoints
- Successfully ran all test suites, all unit and …

🧹 Chore / Rename Applications Edit route

---

apps/api/src/server.ts

Resolve cors error on development.
Environment variable is a string, so we needed to compare if the value is string `false`.

fix(cors): resolve cors not working on development

---

apps/ui/docker/nginx.conf.template

Quick fix!
Updating nginx config for the proxy pass to unblock the `/api` proxy

Fix - remove unused headers in nginx config that break the `/api` proxy.

---

apps/api/drizzle/0002_remove_create_actions.sql

Deletes all Action records with value 'CREATE' to unblock deployment
PR discussion:
https://github.com/Pan-Canadian-Genome-Library/daco/pull/153#discussion_r1936358959
PCGL Dev DB has Action records with value 'CREATE', so on deployment migration to remove 'CREATE' fails
This adds an additional DELETE command to the migration to remove these records before applying the migration
- Label is added for the type of work done in this PR (`feature`, `fix`, …

🕷️ Bug: Delete 'Create' Action records

---

apps/api/src/routes/authRouter.ts

Enable testing of `/manage/applications` by making 'DAC_MEMBER' the default User role
Will be reverted when User roles logic is updated
- Successfully ran all test suites, all unit and integration tests pass
- Unit and integration tests have been added that describe the bug that was fixed or the features that …

Bug: Use Default 'DAC_MEMBER' User Role

---

apps/api/README.md
apps/api/drizzle.config.ts
apps/api/src/db/schemas/agreements.ts
apps/api/src/db/schemas/applicationActions.ts
apps/api/src/db/schemas/applicationContents.ts
apps/api/src/db/schemas/applications.ts
apps/api/src/db/schemas/collaborators.ts
apps/api/src/db/schemas/files.ts
apps/api/src/db/schemas/index.ts
apps/api/src/db/schemas/revisionRequests.ts
apps/api/tsconfig.json

Updates in [220](https://github.com/Pan-Canadian-Genome-Library/daco/pull/220) have removed the `/dist` folder for API
Drizzle was configured to read from `/dist`
This PR updates the config to instead read from `src/db`
Also recent Drizzle updates allow us to use `ts` extensions which previously was not working
Tested and confirmed that DBML generation & Drizzle Kit functions are both working
- Updates Drizzle Config path
- Updates DB imports to use TS
- Label is added for each package/app that is modified (`api`, `ui`, `data-model`, …

Bug: Update Drizzle Config to read from `src`

---

apps/api/src/controllers/applicationController.ts
apps/api/src/resources/swagger.yaml
apps/api/src/routes/application-router.ts
apps/api/src/service/applicationService.ts
apps/api/src/service/types.ts
apps/api/tests/api/application-api.test.ts

[Revisions from PR discussion](https://github.com/Pan-Canadian-Genome-Library/daco/pull/217/)
- Correct type usage 
- Remove 'comments' field
- Return revision record?
- Revision Service?
- Zod Request Validation
- https://github.com/Pan-Canadian-Genome-Library/daco/issues/116
- https://github.com/Pan-Canadian-Genome-Library/daco/issues/118
- Remove 'comments' field: `comments` is a single field on the revisionRequest, schema and in the UI mockups it shares the same modal as the other fields. So I think it makes sense to group `comments` with all the `reviewData` in req.body rather than having them separate. I don't think we need `comments || comments_str`
- Change `reviewData` to `revisionData`
- Flatten Request Body object
- Correct type usage: `service.createRevisionRequest` was using …

Chore: Revisions to PR #217

---

apps/ui/src/components/pages/application/SectionFooter.tsx
apps/ui/src/pages/applications/sections/sign.tsx

onSubmit functionality was removed without accounting for usage on `Sign and Sumbit` section. Re-add Optional Prop SignSubmitHandler to SectionFooter 
- https://github.com/Pan-Canadian-Genome-Library/daco/issues/210#event-16775037865
- add `signSubmitHandler` optional prop to `SectionFooter` component
- …

fix: Re-add Optional SignSubmitHandler to Sectionfooter

---

apps/api/src/controllers/applicationController.ts
apps/api/src/resources/swagger.yaml
apps/api/src/routes/applicationRouter.ts
apps/api/src/utils/aliases.ts
apps/api/tests/api/application-controller.test.ts
packages/validation/src/routes/applicationRoutes.ts

Adds the ability for Applicants to withdraw applications while in `REP_REVIEW` or `DAC_REVIEW` states, along with adding a DTO object for its return. It also includes a small fix for another test which was failing.
- https://github.com/Pan-Canadian-Genome-Library/daco/issues/303
- Added new endpoint `POST /:applicationId/withdraw` which allows an Applicant to withdraw an Application if within the correct states
- Application can only be withdrawn if in `DAC_REVIEW` or `REP_REVIEW`, other states will return a 400 error on failure.
- Added DTO object for APIs returning the basic (non-joined) application record. Other APIs should be updated to use this in another PR.
- Added appropriate tests, and updated swagger documentation.  
Before running these changes, you will need to rebuild the …

feat: 📤 Withdraw Application API

---

apps/ui/src/components/pages/dashboard/cards/NewApplicationCard.tsx

#348 : Make the entire "Start a New Application" card clickable
Made the entire "Start a New Application" card clickable, so that clicking anywhere on the card — not just the "Get Started" button — will trigger the application start action.
- Updated the ApplicationCard component to wrap the entire card in a clickable element (<Link> or onClick handler depending on implementation).
- Ensured both the card content and the "Get Started" button trigger the same navigation event.
- Updated relevant styling to show a pointer cursor on hover over the whole card.
- No new packages added.
-` ApplicationCard `handles both mouse and keyboard interactions, and follows the same ARIA-compliant pattern which have there with Enter and Space triggering the action.
Before running these changes, you will …

#348: Make the entire "Start a New Application" card clickable

---

apps/ui/src/api/apiUtils.ts
apps/ui/src/api/mutations/useCloseApplication.ts
apps/ui/src/api/mutations/useCreateSignature.ts
apps/ui/src/api/queries/useGetApplicationList.ts
apps/ui/src/components/pages/ErrorPage.tsx
apps/ui/src/components/pages/dashboard/cards/ApplicationCard.tsx
apps/ui/src/pages/dashboard.tsx

Updates the get applications list query to be set to a page size of 100. This allows up to 100 applications card to be displayed to the user. It's unlikely they'll ever hit this. We do not have mocks for how pagination will look, this may be a thing post-mvp. 
This ticket also updates the sorting so that DAC_REVIEW things remain at the top.
- https://github.com/Pan-Canadian-Genome-Library/daco/issues/358
- Updates the Dashboard page API call to pass in a pageSize of 100
- Also adds sorting by status, and last update to make the sorting of the cards more sensible.
- Fixes various type errors. 
- The PR title is properly formatted to match the pattern: `#{TicketNumber}: Description …

#358: Increase Query Page Size on `/dashboard`

---

apps/api/src/routes/applicationRouter.ts
apps/ui/src/i18n/locale/en/enModals.json

Updates the withdraw modal text to match the text provided in the Figma mock-up. I think this might have been a merge conflict resolution issue. 
- #303 
- Updated withdraw modal text in `enModals.json` to match the Figma mockup.
- Successfully ran all test suites, all unit and integration tests pass

#303: Update Withdraw Modal Text

---

apps/api/src/routes/collaboratorsRouter.ts
apps/ui/src/api/mutations/useAddCollaborator.ts
apps/ui/src/pages/AppRouter.tsx
packages/request-utils/src/types.ts

Made the API always return a `409` to differentiate from regular invalid request and one that is a duplicate
- Successfully ran all test suites, all unit and integration tests pass

hotfix: :adhesive_bandage: Collaborators UI was displaying incorrect error message

---

apps/ui/src/components/pages/NotFound.tsx
apps/ui/src/i18n/locale/en/enTranslations.json
apps/ui/src/pages/AppRouter.tsx

Creates a new 404 Not Found page for any unmatched URLs in the Router. It also harmonizes the styling for the existing error pages (Unauthorized, Bad Request, Server Error, etc...) to the style used in the 404 page.
- #402 
- ✨ Created **`NotFound.tsx`** which contains the new Not Found page
- Added it to the top of `AppRouter.tsx` with a "*" to catch all unmatched routes
- 🌸 Made all other error pages use a similar style to the new 404 page and beautified / harmonized the styling so they'd all look the same
- Aligned `Skeleton` loading and Error pages properly to the top navigation bar.
- <img width="1912" alt="404 Page Demo" src="https://github.com/user-attachments/assets/59c950ba-5cd7-46ae-8e77-6f23ff63c3ee" />
- <img width="1912" alt="403 Unauthorized Page Demo " …

#402: Handle 404s & Harmonize Error Page Styling

---

apps/ui/src/components/pages/NotFound.tsx
apps/ui/src/pages/AppRouter.tsx

At the request of QA, instead of redirecting the user on the 404 page back to the root homepage (/), when they click "Back to homepage", we now redirect them to /dashboard.
Despite always going to /dashboard, the route will actually redirect the appropriate "homepage" for the user since this protected route is set to redirect to /login/redirect on role match failure which determines the correct routing action for the user type.
- https://github.com/Pan-Canadian-Genome-Library/daco/issues/402
- Redirected users to `/dashboard` not `/` when they click "Back to Homepage" on the 404 page.
- Ordered the 404 page to the bottom of `AppRouter`, not needed but good for organization. 
- The …

#402: Address QA Feedback, Redirect users to `/dashboard` upon clicking "Back To Homepage" button

---

apps/api/src/routes/applicationRouter.ts
apps/ui/src/components/pages/manage/ManagementDashboard.tsx
apps/ui/src/components/pages/manage/RowCount.tsx
apps/ui/src/i18n/locale/en/enTranslations.json
apps/ui/src/pages/manage/applications/index.tsx

Removes "Dashboard" subtext from Manage Applications page, adds "Show X Rows" button. Fixes table showing country as its ISO code instead of name.
- https://github.com/Pan-Canadian-Genome-Library/daco/issues/128
- `/manage/applications/index.tsx` - Removed "Dashboard" subtext from from top of page
- ✨ New component - `RowCount.tsx` - adds a "Show X Rows" component to the bottom of table
- Changes to `ManagementDashboard.tsx` and `index.tsx` to add `rows` query param and appropriate validation.
- Note - positioned using transform, this is due to a weird issue with `<Dropdown/>` comps and using margin or padding.
- 🔧 Fixes table displaying country ISO code (ex. `CAN`) instead of country name (ex. `Canada`)
- I have run the application locally and …

#128: QA Fixes for Manage Applications page & Add page count

---

apps/ui/src/components/TextList.tsx
apps/ui/src/components/pages/application/ApplicationViewerHeader.tsx
apps/ui/src/components/pages/application/SignatureViewer.tsx
apps/ui/src/components/pages/application/form-components/ESignature.tsx
apps/ui/src/components/pages/application/signature-views/ApplicantSignatureView.tsx
apps/ui/src/components/pages/application/signature-views/DacSignatureView.tsx
apps/ui/src/components/pages/application/signature-views/RepSignatureView.tsx
apps/ui/src/components/pages/application/utils/useSignatureForm.ts
apps/ui/src/components/pages/application/utils/validators.ts
apps/ui/src/i18n/locale/en/enSection.json
apps/ui/src/i18n/locale/en/enTranslations.json
apps/ui/src/pages/applications/sections/sign.tsx

Update sign and submit page to new UI/UX design
- https://github.com/Pan-Canadian-Genome-Library/daco/issues/424
- Move download application pdf logic to Application Header
- Create `SignatureViewer` Component
- Create Views
- ApplicantSignatureView
- RepSignatureView
- DacSignatureView
- Relocate signature logic into a custom hook
- Add en translations for the new views
- Label is added for the type of work done in this PR (`feature`, `fix`, …

#424: Sign and Submit Section Refactor

---

apps/api/src/routes/applicationRouter.ts
apps/ui/src/components/pages/application/SectionMenu.tsx
apps/ui/src/components/pages/application/SectionMenuItem.tsx
apps/ui/src/components/pages/application/utils/IconSelector.tsx
apps/ui/src/pages/applications/index.tsx

Resolve users outside of APPLICANT to be able to make changes to the application.
- https://github.com/Pan-Canadian-Genome-Library/daco/issues/425
- Add APPLICANT role to authmiddle where for `/edit` post endpoint
- Add additional logic to check the user role as well as the application-state lifecycle for page redirect
- If the application-state is not DRAFT or if the user is not an APPLICANT, push back to view mode
- Add additional logic to check the user role on sidemenu icon selector
- Add additional logic to disable revision logic depending on user role
- if the user role is NOT applicant, then the sidemenu will display a lock for all sections (minus sign for reps) 
- if the user role is NOT applicant, pass empty revision object in Outlet Context
- I have performed a self review of …

#425: Resolve Application Editable by DAC Users

---

apps/api/src/controllers/applicationController.ts
apps/api/src/docs/application-api.yaml
apps/api/src/routes/applicationRouter.ts
apps/api/src/routes/types.ts
apps/api/src/service/applicationService.ts
apps/api/tests/api/application-controller.test.ts
apps/ui/src/api/queries/useGetApplicationList.ts
apps/ui/src/pages/dashboard.tsx

Update dashboard sorting to have:
- the apps that require actions are always listed at the top.
- the last created apps should be listed to the top.
- https://github.com/Pan-Canadian-Genome-Library/daco/issues/439
- Update `useGetListApplication.ts` to optionally take param `isApplicantView`
- Update `listApplications` Application service to for filtering/sorting  
- applicantView === true: sort applications that are in request revisions states to the top
- applicantView === false: sort applications that are DAC_REVIEW to top
- by default it is false 
- Links are included to all …

#439: Update Application Sorting Rules

---

apps/ui/src/pages/manage/applications/index.tsx

On dev, for some reason the `antd` version shoes a size changer component by default on the `manage/applications` page. This is not present on local. This seems to be a change that could have been introduced in `antd` version `5.21.0`.
- N/A
- 🩹 add `showSizeChanger` set to false to prevent it being shown by default on the manage page. This is a weird bug introduced by antd on Dev.
- Label is added for the type of work done in this PR (`feature`, …

fix: 🩹 `showSizeChanger` should be set to false
